version: '3'

services:
  app:
    image: ${IMAGE_NAME}
    stdin_open: true
    tty: true
    volumes:
      - ./tests:/opt/project/app/tests
      - ./.flake8:/opt/project/app/.flake8
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
      MINIO_BUCKET_NAME: imagedetection
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
