version: '3'

services:
  app:
    image: ${IMAGE_NAME}
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/project/app
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
      MINIO_BUCKET_NAME: imagedetection
    working_dir: /opt/project/app
    command: sh
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2019-12-19T22-52-26Z
    command: server /data
    volumes:
      - ./__docker/minio-data:/data
    environment:
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
    ports:
      - 19000:9000
