version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: amd
      args:
        MODEL_URL: 'http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz'
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/project/app
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
      MINIO_BUCKET_NAME: imagedetection
    working_dir: /opt/project/app
    command: sh
    depends_on:
      - minio

  minio:
    image: minio/minio:RELEASE.2019-12-19T22-52-26Z
    command: server /data
    volumes:
      - ./__docker/minio-data:/data
    environment:
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
    ports:
      - 19000:9000

  mosquitto:
    image: eclipse-mosquitto:1.6.8
    volumes:
      - ./__docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 19001:1883
