version: 2.1

jobs:
  build_and_test_image:
    # machine: true
    machine:
      image: ubuntu-1604:202004-01
    environment:
      IMAGE_NAME: image-object-detection
    parameters:
      model_url:
        type: string
      docker_tag:
        type: string

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - checkout

      - run:
          name: Docker login
          command: docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASS}

      - run:
          name: Build image
          command: docker build --build-arg MODEL_URL="<< parameters.model_url >>" --target amd -t ${IMAGE_NAME} .

      - run:
          name: Run flake8
          command: docker-compose -f docker-compose-test.yml run --rm app /bin/bash -c "pip3 install flake8 && flake8 image_object_detection tests"

      - run:
          name: Run tests
          command: docker-compose -f docker-compose-test.yml run --rm app python -m unittest discover tests *_test.py

      - run:
          name: Tag image
          command: docker tag ${IMAGE_NAME} tkislan/image-object-detection:<< parameters.docker_tag >>

      - run:
          name: Push image
          command: docker push tkislan/image-object-detection:<< parameters.docker_tag >>
      
      - run:
          name: List images
          command: docker images

      - run:
          name: Setup Qemu
          command: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - run:
          name: Build Jetson image
          command: docker build --build-arg MODEL_URL="<< parameters.model_url >>" -t tkislan/image-object-detection:jetson-<< parameters.docker_tag >> .
      
      - run:
          name: List images
          command: docker images
      
      - run:
          name: Push image
          command: docker push tkislan/image-object-detection:jetson-<< parameters.docker_tag >>

workflows:
  version: 2
  build:
    jobs:
      # - build_and_test_image:
      #     name: Model ssdlite-mobilenet-v2-coco
      #     model_url: 'http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz'
      #     docker_tag: 'ssdlite-mobilenet-coco-latest'
      - build_and_test_image:
          name: Model ssd-mobilenet-v2-coco
          model_url: 'http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2017_11_17.tar.gz'
          docker_tag: 'ssd-mobilenet-v2-coco-latest'
      # - build_and_test_image:
      #     name: Model ssd-mobilenet-v1-coco
      #     model_url: 'http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz'
      #     docker_tag: 'ssd-mobilenet-coco-latest'
    #   - build_and_test_image:
    #       name: Model faster-rcnn-inception-v2-coco
    #       model_url: 'http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz'
    #       docker_tag: 'faster-rcnn-inception-coco-latest'
    #   - build_and_test_image:
    #       name: Model ssd-resnet50-v1-coco
    #       model_url: 'http://download.tensorflow.org/models/object_detection/ssd_resnet50_v1_fpn_shared_box_predictor_640x640_coco14_sync_2018_07_03.tar.gz'
    #       docker_tag: 'ssd-resnet50-coco-latest'
    #   - build_and_test_image:
    #       name: Model faster-rcnn-resnet101-kitti
    #       model_url: 'http://download.tensorflow.org/models/object_detection/faster_rcnn_resnet101_kitti_2018_01_28.tar.gz'
    #       docker_tag: 'faster-rcnn-resnet101-kitti-latest'
