version: 2.1

jobs:
  build_and_test_image:
    machine: true
    environment:
      IMAGE_NAME: image-object-detection
    parameters:
      model_url:
        type: string
      docker_tag:
        type: string

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - checkout

      - run:
          name: Build image
          command: docker build --build-arg MODEL_URL="<< parameters.model_url >>" -t ${IMAGE_NAME} .

      - run:
          name: Run flake8
          command: docker-compose -f docker-compose-test.yml run pip install flake8 && app flake8 image_object_detection tests

      - run:
          name: Run tests
          command: docker-compose -f docker-compose-test.yml run app python -m unittest discover tests *_test.py

      - run:
          name: Tag image
          command: docker tag ${IMAGE_NAME} tkislan/image-object-detection:<< parameters.docker_tag >>

workflows:
  version: 2
  build:
    jobs:
      - build_and_test_image:
          name: Model ssdlite-mobilenet-v2-coco
          model_url: 'http://download.tensorflow.org/models/object_detection/ssdlite_mobilenet_v2_coco_2018_05_09.tar.gz'
          docker_tag: 'ssdlite-mobilenet-latest'
      - build_and_test_image:
          name: Model faster-rcnn-inception-v2-coco
          model_url: 'http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2018_01_28.tar.gz'
          docker_tag: 'faster-rcnn-inception-latest'
