version: 2
jobs:
  run_tests:
    docker:
      - image: tkislan/image-object-detection
      - image: minio/minio:RELEASE.2018-12-27T18-33-08Z
        command: server /export
        environment:
          MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
          MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
    environment:
      MINIO_HOST: 127.0.0.1
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: SO9KNO6YT9OGE39PQCZW
      MINIO_SECRET_KEY: EzH5iGs3qbJr1MwIMf2AUyfqzewgd2qgrk9+i+vU
      MINIO_BUCKET_NAME: imagedetection
    working_directory: ~/project
    steps:
      - run:
          name: Install Git
          command: apt-get update && apt-get install -y git ssh

      - checkout

      - run:
          name: Set PYTHONPATH environment variable
          command: echo 'export PYTHONPATH=${PYTHONPATH}:${HOME}/project/src' >> $BASH_ENV

      - run:
          name: Install Test dependencies
          command: pip install flake8

      - run:
          name: Run flake8
          command: flake8 src/ tests/

      - run:
          name: Run tests
          command: python -m unittest discover tests "*_test.py"

  build_images:
    machine: true
    steps:
      - checkout

      - run:
          name: Build Image
          command: docker build -t tkislan/image-object-detection .

workflows:
  version: 2
  build:
    jobs:
      - run_tests
      - build_image:
          requires:
            - run_tests
