version: '2.4'
services:
  app:
    network_mode: host
    environment:
      HISTFILE: '/root/.bashhistory/.bash_history'
    volumes:
      - .:/opt/project/app
      - vscode-server-extensions:/root/.vscode-server/extensions
      - bash-history:/root/.bashhistory
      - $HOME/.ssh:/root/.ssh

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  vscode-server-extensions:
  bash-history:
